-- Seed 54 SEO keywords from the old hardcoded config
-- Safe to run multiple times (ON CONFLICT DO NOTHING)

INSERT INTO public.seo_keywords (slug, label, include_in_sitemap_towns, template_overrides, sort_order) VALUES
  ('rent-a-car', 'Rent a Car', true, NULL, 1),
  ('car-on-rent', 'Car on Rent', true, NULL, 2),
  ('car-hire', 'Car Hire', true, NULL, 3),
  ('rent-a-vehicle', 'Rent a Vehicle', false, NULL, 4),
  ('online-car-booking', 'Online Car Booking', false, NULL, 5),
  ('rent-vehicle-online', 'Rent Vehicle Online', false, NULL, 6),
  ('car-rental-platform', 'Car Rental Platform', false, NULL, 7),
  ('vehicle-booking-platform', 'Vehicle Booking Platform', false, NULL, 8),
  ('affordable-car-rental', 'Affordable Car Rental', false, NULL, 9),
  ('cheap-car-rental', 'Cheap Car Rental', false, NULL, 10),
  ('best-car-rental', 'Best Car Rental', false, NULL, 11),
  ('low-cost-car-rental', 'Low Cost Car Rental', false, NULL, 12),
  ('car-rental-deals', 'Car Rental Deals', false, NULL, 13),
  ('car-rental-prices', 'Car Rental Prices', false, NULL, 14),
  ('daily-car-rental', 'Daily Car Rental', false, NULL, 15),
  ('short-term-car-rental', 'Short Term Car Rental', false, NULL, 16),
  ('long-term-car-rental', 'Long Term Car Rental', false, NULL, 17),
  ('hourly-car-rental', 'Hourly Car Rental', false, NULL, 18),
  ('reliable-car-rental', 'Reliable Car Rental', false, NULL, 19),
  ('trusted-car-rental', 'Trusted Car Rental', false, NULL, 20),
  ('verified-car-rental', 'Verified Car Rental', false, NULL, 21),
  ('best-car-rental-service', 'Best Car Rental Service', false, NULL, 22),
  ('top-car-rental-company', 'Top Car Rental Company', false, NULL, 23),
  ('instant-car-booking', 'Instant Car Booking', false, NULL, 24),
  ('quick-car-booking', 'Quick Car Booking', false, NULL, 25),
  ('car-rental-near-me', 'Car Rental Near Me', false, NULL, 26),
  ('rent-car-now', 'Rent Car Now', false, NULL, 27),
  ('travel-car-rental', 'Travel Car Rental', false, NULL, 28),
  ('tour-car-rental', 'Tour Car Rental', false, NULL, 29),
  ('family-car-rental', 'Family Car Rental', false, NULL, 30),
  ('business-car-rental', 'Business Car Rental', false, NULL, 31),
  ('car-rental-with-driver', 'Car Rental with Driver', false, NULL, 32),
  ('car-rental-without-driver', 'Car Rental without Driver', false, NULL, 33),
  ('car-rental-marketplace', 'Car Rental Marketplace', false, NULL, 34),
  ('vehicle-rental-marketplace', 'Vehicle Rental Marketplace', false, NULL, 35),
  ('personal-car-rental', 'Personal Car Rental', false, NULL, 36),
  ('commercial-car-rental', 'Commercial Car Rental', false, NULL, 37),
  ('airport-transfer', 'Airport Transfer', true,
    '{"city": {"h1": "Airport Transfer in {city} — Reliable Pick & Drop", "title": "Airport Transfer in {city} | Professional Drivers, 24/7 Service", "description": "Book airport transfers in {city} with professional drivers. Ideal for late-night arrivals and family travel. Flight tracking included. Pay only a small advance."}}',
    38),
  ('self-drive-car-rental', 'Self Drive Car Rental', false, NULL, 39),
  ('wedding-car-rental', 'Wedding Car Rental', false, NULL, 40),
  ('airport-transfer-services', 'Airport Transfer Services', false, NULL, 41),
  ('monthly-daily-car-rental', 'Monthly & Daily Car Rental', false, NULL, 42),
  ('luxury-economy-budget-cars', 'Luxury, Economy & Budget Cars', false, NULL, 43),
  ('bus-coaster-rental', 'Bus & Coaster Rental', false, NULL, 44),
  ('tour-travel-vehicles', 'Tour & Travel Vehicles', false, NULL, 45)
ON CONFLICT (slug) DO NOTHING;
